---

- name: Get the timestamp
  set_fact:
    fixed_timestamp: "{{ ansible_date_time.iso8601_basic_short }}"

- name: Copy all backup files to backup server
  synchronize:
    src: "{{ backup_temp_dir }}/*"
    dest: "{{ backup_temp_dir }}"
  delegate_to: controller

- name: Create an archive of the filesystem
    script: |
      /bin/tar --ignore-failed-read --xattrs \
        -zcf {{ backup_temp_dir }}/overcloud-backup-{{ fixed_timestamp }}.tar \
        {{ backup_temp_dir }}/*

- name: Execute post-backup script
  shell: "{{ backup_post_script }} >> {{ backup_post_log }}"
  when: run_post_script
